/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/node-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNodeTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/node-types/{type}/{version}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveNodeType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWorkflows"];
        put?: never;
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        get: operations["getWorkflow"];
        put: operations["saveWorkflowDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/template": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        get: operations["exportWorkflowTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/test-runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runWorkflowDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        get: operations["listWorkflowRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-templates/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewWorkflowTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow-templates/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importWorkflowTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["AgentSlug"];
            };
            cookie?: never;
        };
        get: operations["getAgentManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{slug}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["AgentSlug"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponse: {
            status: string;
        };
        Position: {
            x: number;
            y: number;
        };
        Node: {
            id: string;
            type: string;
            typeVersion: string;
            position: components["schemas"]["Position"];
            config: {
                [key: string]: unknown;
            };
        };
        Edge: {
            id: string;
            source: string;
            sourcePort: string;
            target: string;
            targetPort: string;
        };
        Graph: {
            /** @constant */
            schemaVersion: 1;
            nodes: components["schemas"]["Node"][];
            edges: components["schemas"]["Edge"][];
        };
        PortDefinition: {
            key: string;
            title: string;
            /** @enum {string} */
            type: "string" | "number" | "boolean" | "json" | "any";
            required: boolean;
            /** @enum {string} */
            cardinality: "one" | "single-active";
        };
        ResolvedPorts: {
            inputs: components["schemas"]["PortDefinition"][];
            outputs: components["schemas"]["PortDefinition"][];
        };
        NodeDefinition: {
            type: string;
            version: string;
            title: string;
            description: string;
            category: string;
            configSchema: {
                [key: string]: unknown;
            };
            inputs: components["schemas"]["PortDefinition"][];
            outputs: components["schemas"]["PortDefinition"][];
            capabilities?: ("network" | "secrets" | "filesystem-read" | "filesystem-write")[];
        };
        ValidationIssue: {
            code: string;
            message: string;
            nodeId?: string;
            edgeId?: string;
            path?: string;
        };
        WorkflowTemplate: {
            /** @constant */
            apiVersion: "agent-studio.dev/v1alpha1";
            /** @constant */
            kind: "WorkflowTemplate";
            metadata: components["schemas"]["WorkflowTemplateMetadata"];
            spec: components["schemas"]["WorkflowTemplateSpec"];
        };
        WorkflowTemplateMetadata: {
            name: string;
            description: string;
        };
        WorkflowTemplateSpec: {
            graph: components["schemas"]["Graph"];
        };
        PreviewWorkflowTemplateRequest: {
            template: components["schemas"]["WorkflowTemplate"];
        };
        ImportWorkflowTemplateRequest: {
            template: components["schemas"]["WorkflowTemplate"];
            name: string;
            slug: string;
            description: string;
        };
        WorkflowTemplatePreview: {
            valid: boolean;
            metadata: components["schemas"]["WorkflowTemplateMetadata"];
            summary: components["schemas"]["WorkflowTemplateSummary"];
            issues: components["schemas"]["ValidationIssue"][];
        };
        WorkflowTemplateSummary: {
            nodeCount: number;
            edgeCount: number;
            inputSchema: {
                [key: string]: unknown;
            };
            nodeTypes: components["schemas"]["WorkflowTemplateNodeTypeSummary"][];
        };
        WorkflowTemplateNodeTypeSummary: {
            type: string;
            version: string;
            title: string;
            count: number;
            available: boolean;
            capabilities: ("network" | "secrets" | "filesystem-read" | "filesystem-write")[];
        };
        Workflow: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description: string;
            draftGraph: components["schemas"]["Graph"];
            /** Format: int64 */
            draftRevision: number;
            /** Format: uuid */
            publishedVersionId?: string | null;
            publishedVersion?: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkflowVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workflowId: string;
            version: number;
            graph: components["schemas"]["Graph"];
            inputSchema: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AgentManifest: {
            /** Format: uuid */
            workflowVersionId: string;
            version: number;
            title: string;
            description: string;
            inputSchema: {
                [key: string]: unknown;
            };
        };
        Run: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            workflowId: string;
            /** Format: uuid */
            workflowVersionId?: string | null;
            /** Format: int64 */
            draftRevision?: number | null;
            graphSnapshot?: components["schemas"]["Graph"] | null;
            /** @enum {string} */
            mode: "test" | "published";
            /** @enum {string} */
            status: "running" | "completed" | "failed" | "cancelled";
            input: unknown;
            output?: unknown;
            error?: components["schemas"]["PublicError"] | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
        };
        NodeRun: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            runId: string;
            nodeId: string;
            nodeType: string;
            status: string;
            input?: unknown;
            output?: unknown;
            error?: components["schemas"]["PublicError"] | null;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            endedAt?: string | null;
        };
        RunEvent: {
            /** Format: int64 */
            sequence: number;
            /** @enum {string} */
            type: "run.started" | "node.started" | "node.completed" | "node.failed" | "node.skipped" | "node.cancelled" | "run.completed" | "run.failed" | "run.cancelled";
            /** Format: uuid */
            runId: string;
            nodeId?: string;
            status?: string;
            input?: unknown;
            output?: unknown;
            error?: components["schemas"]["PublicError"] | null;
            /** Format: date-time */
            timestamp: string;
        };
        PublicError: {
            code: string;
            /** @enum {string} */
            kind?: "config" | "input" | "temporary" | "canceled" | "internal";
            message: string;
            nodeId?: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
            requestId?: string;
            issues?: components["schemas"]["ValidationIssue"][];
        };
        CreateWorkflowRequest: {
            name: string;
            slug: string;
            description?: string;
        };
        SaveDraftRequest: {
            /** Format: int64 */
            draftRevision: number;
            graph: components["schemas"]["Graph"];
        };
        DraftRunRequest: {
            /** Format: int64 */
            draftRevision: number;
            input: {
                [key: string]: unknown;
            };
        };
        AgentRunRequest: {
            /** Format: uuid */
            workflowVersionId: string;
            input: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 稳定错误响应 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        WorkflowID: string;
        AgentSlug: string;
        NodeType: string;
        NodeVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务就绪 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    listNodeTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 节点定义 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDefinition"][];
                };
            };
        };
    };
    resolveNodeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: components["parameters"]["NodeType"];
                version: components["parameters"]["NodeVersion"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    config: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description 解析后的端口 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedPorts"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listWorkflows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工作流列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"][];
                };
            };
        };
    };
    createWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkflowRequest"];
            };
        };
        responses: {
            /** @description 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 工作流草稿 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    saveWorkflowDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDraftRequest"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    exportWorkflowTemplate: {
        parameters: {
            query: {
                draftRevision: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规范化工作流模板下载 */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTemplate"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    validateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 校验结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        valid: boolean;
                        issues: components["schemas"]["ValidationIssue"][];
                    };
                };
            };
        };
    };
    runWorkflowDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRunRequest"];
            };
        };
        responses: {
            /** @description 每行一个 RunEvent 的 NDJSON 流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    publishWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    draftRevision: number;
                };
            };
        };
        responses: {
            /** @description 不可变工作流版本 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowVersion"];
                };
            };
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    listWorkflowRuns: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["WorkflowID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行记录 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
        };
    };
    previewWorkflowTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewWorkflowTemplateRequest"];
            };
        };
        responses: {
            /** @description 模板兼容性预览 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowTemplatePreview"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    importWorkflowTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportWorkflowTemplateRequest"];
            };
        };
        responses: {
            /** @description 已创建未发布工作流草稿 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            422: components["responses"]["Error"];
            500: components["responses"]["Error"];
        };
    };
    getAgentManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["AgentSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前发布页 Manifest */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentManifest"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    runAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["AgentSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRunRequest"];
            };
        };
        responses: {
            /** @description 每行一个 RunEvent 的 NDJSON 流 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/x-ndjson": string;
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 运行详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        run: components["schemas"]["Run"];
                        nodeRuns: components["schemas"]["NodeRun"][];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
