package nodegen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/yyl1212/agent-studio/internal/nodemanifest"
)

type Generator struct {
	ListPackage func(ctx context.Context, root, importPath string) error
}

func (generator Generator) Generate(ctx context.Context, root string, manifest nodemanifest.Manifest, outputPath string) (bool, error) {
	nodes := append([]nodemanifest.NodePackage(nil), manifest.Nodes...)
	sort.Slice(nodes, func(left, right int) bool {
		return nodes[left].Package < nodes[right].Package
	})
	listPackage := generator.ListPackage
	if listPackage == nil {
		listPackage = listGoPackage
	}
	for _, node := range nodes {
		if err := listPackage(ctx, root, node.Package); err != nil {
			return false, fmt.Errorf("validate node package %s: %w", node.Package, err)
		}
	}
	generated, err := render(nodes)
	if err != nil {
		return false, err
	}
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Join(root, outputPath)
	}
	existing, err := os.ReadFile(outputPath)
	if err == nil && bytes.Equal(existing, generated) {
		return false, nil
	}
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, fmt.Errorf("read generated nodes %s: %w", outputPath, err)
	}
	if err := writeAtomic(outputPath, generated); err != nil {
		return false, err
	}
	return true, nil
}

func render(nodes []nodemanifest.NodePackage) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by agent-studio generate; DO NOT EDIT.\n\n")
	source.WriteString("package generated\n\n")
	if len(nodes) == 0 {
		source.WriteString("import \"github.com/yyl1212/agent-studio/sdk/go/agentnode\"\n\n")
		source.WriteString("func RegisterNodes(agentnode.Registrar) error {\n\treturn nil\n}\n")
	} else {
		source.WriteString("import (\n\t\"fmt\"\n\n")
		for index, node := range nodes {
			_, _ = fmt.Fprintf(&source, "\tnode%d %q\n", index, node.Package)
		}
		source.WriteString("\t\"github.com/yyl1212/agent-studio/sdk/go/agentnode\"\n)\n\n")
		source.WriteString("func RegisterNodes(registrar agentnode.Registrar) error {\n")
		for index, node := range nodes {
			_, _ = fmt.Fprintf(&source, "\tif err := node%d.Register(registrar); err != nil {\n", index)
			_, _ = fmt.Fprintf(&source, "\t\treturn fmt.Errorf(%q, err)\n", "register "+node.Package+": %w")
			source.WriteString("\t}\n")
		}
		source.WriteString("\treturn nil\n}\n")
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated nodes: %w", err)
	}
	return formatted, nil
}

func listGoPackage(ctx context.Context, root, importPath string) error {
	command := exec.CommandContext(ctx, "go", "list", "-mod=readonly", importPath)
	command.Dir = root
	command.Env = overrideEnvironment(os.Environ(), map[string]string{
		"CGO_ENABLED": "0",
		"GOPROXY":     "off",
	})
	output, err := command.CombinedOutput()
	if err != nil {
		return fmt.Errorf("go list: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func overrideEnvironment(environment []string, replacements map[string]string) []string {
	updated := make([]string, 0, len(environment)+len(replacements))
	for _, entry := range environment {
		key, _, found := strings.Cut(entry, "=")
		if found {
			if _, replace := replacements[key]; replace {
				continue
			}
		}
		updated = append(updated, entry)
	}
	keys := make([]string, 0, len(replacements))
	for key := range replacements {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		updated = append(updated, key+"="+replacements[key])
	}
	return updated
}

func writeAtomic(path string, data []byte) (returnErr error) {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create generated nodes directory %s: %w", directory, err)
	}
	temporary, err := os.CreateTemp(directory, ".nodes_gen.go-*")
	if err != nil {
		return fmt.Errorf("create generated nodes temporary file: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() {
		if returnErr != nil {
			_ = temporary.Close()
			_ = os.Remove(temporaryPath)
		}
	}()
	if err := temporary.Chmod(0o644); err != nil {
		return fmt.Errorf("chmod generated nodes temporary file: %w", err)
	}
	if _, err := temporary.Write(data); err != nil {
		return fmt.Errorf("write generated nodes temporary file: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		return fmt.Errorf("sync generated nodes temporary file: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close generated nodes temporary file: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace generated nodes %s: %w", path, err)
	}
	return nil
}
