package nodegen

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yyl1212/agent-studio/internal/nodemanifest"
	"github.com/yyl1212/agent-studio/sdk/go/agentnode"
)

func TestGenerateIsSortedAndStable(t *testing.T) {
	root := t.TempDir()
	output := filepath.Join(root, "generated", "nodes_gen.go")
	var validated []string
	generator := Generator{ListPackage: func(_ context.Context, _, importPath string) error {
		validated = append(validated, importPath)
		return nil
	}}
	manifest := nodemanifest.Manifest{APIVersion: agentnode.APIVersion, Nodes: []nodemanifest.NodePackage{
		{Package: "example.com/zeta"},
		{Package: "example.com/alpha"},
	}}
	changed, err := generator.Generate(context.Background(), root, manifest, output)
	if err != nil || !changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	if got, want := strings.Join(validated, ","), "example.com/alpha,example.com/zeta"; got != want {
		t.Fatalf("validated=%q, want %q", got, want)
	}
	first, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	before, err := os.Stat(output)
	if err != nil {
		t.Fatal(err)
	}
	want, err := os.ReadFile("testdata/nodes_gen.golden")
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(want) {
		t.Fatalf("generated:\n%s\nwant:\n%s", first, want)
	}
	validated = nil
	changed, err = generator.Generate(context.Background(), root, manifest, output)
	if err != nil || changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	after, err := os.Stat(output)
	if err != nil {
		t.Fatal(err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatalf("mtime changed: before=%v after=%v", before.ModTime(), after.ModTime())
	}
}

func TestGeneratePreservesOldFileWhenPackageValidationFails(t *testing.T) {
	root := t.TempDir()
	output := filepath.Join(root, "nodes_gen.go")
	if err := os.WriteFile(output, []byte("old-content"), 0o600); err != nil {
		t.Fatal(err)
	}
	wantErr := errors.New("package unavailable")
	generator := Generator{ListPackage: func(_ context.Context, _, importPath string) error {
		if importPath == "example.com/zeta" {
			return wantErr
		}
		return nil
	}}
	manifest := nodemanifest.Manifest{APIVersion: agentnode.APIVersion, Nodes: []nodemanifest.NodePackage{
		{Package: "example.com/alpha"},
		{Package: "example.com/zeta"},
	}}
	changed, err := generator.Generate(context.Background(), root, manifest, output)
	if changed || !errors.Is(err, wantErr) {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	data, readErr := os.ReadFile(output)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if got, want := string(data), "old-content"; got != want {
		t.Fatalf("output=%q, want %q", got, want)
	}
	entries, readDirErr := os.ReadDir(root)
	if readDirErr != nil {
		t.Fatal(readDirErr)
	}
	if len(entries) != 1 || entries[0].Name() != "nodes_gen.go" {
		t.Fatalf("unexpected files after failure: %v", entries)
	}
}

func TestGenerateEmptyManifestProducesCompilableEntryPoint(t *testing.T) {
	root := t.TempDir()
	output := filepath.Join(root, "nodes_gen.go")
	changed, err := (Generator{}).Generate(context.Background(), root, nodemanifest.Manifest{
		APIVersion: agentnode.APIVersion,
		Nodes:      []nodemanifest.NodePackage{},
	}, output)
	if err != nil || !changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by agent-studio generate; DO NOT EDIT.\n\npackage generated\n\nimport \"github.com/yyl1212/agent-studio/sdk/go/agentnode\"\n\nfunc RegisterNodes(agentnode.Registrar) error {\n\treturn nil\n}\n"
	if string(data) != want {
		t.Fatalf("generated:\n%s\nwant:\n%s", data, want)
	}
}
