package nodegen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/yyl1212/agent-studio/internal/nodemanifest"
	"github.com/yyl1212/agent-studio/internal/nodepackage"
	"github.com/yyl1212/agent-studio/internal/safepath"
)

type Generator struct {
	Inspector nodepackage.Inspector
}

type generationGroup struct {
	summary       nodepackage.Summary
	registrations []nodepackage.Registration
}

func (generator Generator) Generate(ctx context.Context, root string, manifest nodemanifest.Manifest, outputPath string) (bool, error) {
	if !filepath.IsAbs(outputPath) {
		outputPath = filepath.Join(root, outputPath)
	}
	if err := safepath.ValidateWriteTarget(root, outputPath); err != nil {
		return false, fmt.Errorf("validate generated nodes target: %w", err)
	}
	importPaths := make([]string, 0, len(manifest.Nodes))
	for _, node := range manifest.Nodes {
		importPaths = append(importPaths, node.Package)
	}
	inspections := generator.Inspector.InspectMany(ctx, root, importPaths)
	grouped := make(map[string]*generationGroup)
	for _, inspection := range inspections {
		if err := inspection.Error(); err != nil {
			return false, fmt.Errorf("inspect node package: %w", err)
		}
		group := grouped[inspection.Record.ModulePath]
		if group == nil {
			group = &generationGroup{summary: inspection.Record.Summary}
			grouped[inspection.Record.ModulePath] = group
		}
		group.registrations = append(group.registrations, inspection.Record.Registration)
	}
	modulePaths := make([]string, 0, len(grouped))
	for modulePath := range grouped {
		modulePaths = append(modulePaths, modulePath)
	}
	sort.Strings(modulePaths)
	groups := make([]generationGroup, 0, len(modulePaths))
	for _, modulePath := range modulePaths {
		group := grouped[modulePath]
		sort.Slice(group.registrations, func(left, right int) bool {
			return group.registrations[left].Package < group.registrations[right].Package
		})
		groups = append(groups, *group)
	}
	generated, err := render(groups)
	if err != nil {
		return false, err
	}
	existing, err := os.ReadFile(outputPath)
	if err == nil && bytes.Equal(existing, generated) {
		return false, nil
	}
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return false, fmt.Errorf("read generated nodes %s: %w", outputPath, err)
	}
	if err := writeAtomic(outputPath, generated); err != nil {
		return false, err
	}
	return true, nil
}

func render(groups []generationGroup) ([]byte, error) {
	var source strings.Builder
	source.WriteString("// Code generated by agent-studio generate; DO NOT EDIT.\n\n")
	source.WriteString("package generated\n\n")
	source.WriteString("import (\n")
	if len(groups) > 0 {
		source.WriteString("\t\"fmt\"\n\n")
	}
	alias := 0
	for _, group := range groups {
		for _, registration := range group.registrations {
			_, _ = fmt.Fprintf(&source, "\tnode%d %q\n", alias, registration.Package)
			alias++
		}
	}
	source.WriteString("\t\"github.com/yyl1212/agent-studio/sdk/go/agentnode\"\n\t\"github.com/yyl1212/agent-studio/sdk/go/nodepackage\"\n)\n\n")
	source.WriteString("type packageRegistry interface {\n\tRegisterPackage(nodepackage.RuntimeRecord, func(agentnode.Registrar) error) error\n}\n\n")
	source.WriteString("func RegisterNodes(registry packageRegistry) error {\n")
	alias = 0
	for groupIndex, group := range groups {
		nodeRefs := make([]nodepackage.NodeRef, 0)
		for _, registration := range group.registrations {
			nodeRefs = append(nodeRefs, registration.Nodes...)
		}
		sort.Slice(nodeRefs, func(i, j int) bool {
			if nodeRefs[i].Type != nodeRefs[j].Type {
				return nodeRefs[i].Type < nodeRefs[j].Type
			}
			return nodeRefs[i].Version < nodeRefs[j].Version
		})
		_, _ = fmt.Fprintf(&source, "\trecord%d := nodepackage.RuntimeRecord{\n\t\tSummary: nodepackage.Summary{\n", groupIndex)
		_, _ = fmt.Fprintf(&source, "\t\t\tName: %q, DisplayName: %q, Version: %q, License: %q, Repository: %q, Source: nodepackage.Source(%q),\n", group.summary.Name, group.summary.DisplayName, group.summary.Version, group.summary.License, group.summary.Repository, group.summary.Source)
		source.WriteString("\t\t},\n\t\tNodes: []nodepackage.NodeRef{\n")
		for _, ref := range nodeRefs {
			_, _ = fmt.Fprintf(&source, "\t\t\t{Type: %q, Version: %q},\n", ref.Type, ref.Version)
		}
		source.WriteString("\t\t},\n\t}\n")
		_, _ = fmt.Fprintf(&source, "\tif err := registry.RegisterPackage(record%d, func(registrar agentnode.Registrar) error {\n", groupIndex)
		for _, registration := range group.registrations {
			_, _ = fmt.Fprintf(&source, "\t\tif err := node%d.Register(registrar); err != nil {\n\t\t\treturn fmt.Errorf(%q, err)\n\t\t}\n", alias, "register "+registration.Package+": %w")
			alias++
		}
		source.WriteString("\t\treturn nil\n\t}); err != nil {\n")
		_, _ = fmt.Fprintf(&source, "\t\treturn fmt.Errorf(%q, err)\n", "register node package "+group.summary.Name+": %w")
		source.WriteString("\t}\n")
	}
	source.WriteString("\treturn nil\n}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated nodes: %w", err)
	}
	return formatted, nil
}

func writeAtomic(path string, data []byte) (returnErr error) {
	directory := filepath.Dir(path)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create generated nodes directory %s: %w", directory, err)
	}
	temporary, err := os.CreateTemp(directory, ".nodes_gen.go-*")
	if err != nil {
		return fmt.Errorf("create generated nodes temporary file: %w", err)
	}
	temporaryPath := temporary.Name()
	defer func() {
		if returnErr != nil {
			_ = temporary.Close()
			_ = os.Remove(temporaryPath)
		}
	}()
	if err := temporary.Chmod(0o644); err != nil {
		return fmt.Errorf("chmod generated nodes temporary file: %w", err)
	}
	if _, err := temporary.Write(data); err != nil {
		return fmt.Errorf("write generated nodes temporary file: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		return fmt.Errorf("sync generated nodes temporary file: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close generated nodes temporary file: %w", err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace generated nodes %s: %w", path, err)
	}
	return nil
}
