package nodegen

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/yyl1212/agent-studio/internal/nodemanifest"
	"github.com/yyl1212/agent-studio/sdk/go/agentnode"
)

func TestGenerateIsSortedAndStable(t *testing.T) {
	root := nodegenRoot(t)
	output := filepath.Join(root, "generated", "nodes_gen.go")
	var validated []string
	generator := Generator{ListPackage: func(_ context.Context, _, importPath string) error {
		validated = append(validated, importPath)
		return nil
	}}
	manifest := nodemanifest.Manifest{APIVersion: agentnode.APIVersion, Nodes: []nodemanifest.NodePackage{
		{Package: "example.com/studio/extensions/zeta"},
		{Package: "example.com/studio/extensions/alpha"},
	}}
	changed, err := generator.Generate(context.Background(), root, manifest, output)
	if err != nil || !changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	if got, want := strings.Join(validated, ","), "example.com/studio/extensions/alpha,example.com/studio/extensions/zeta"; got != want {
		t.Fatalf("validated=%q, want %q", got, want)
	}
	first, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	before, err := os.Stat(output)
	if err != nil {
		t.Fatal(err)
	}
	want, err := os.ReadFile("testdata/nodes_gen.golden")
	if err != nil {
		t.Fatal(err)
	}
	if string(first) != string(want) {
		t.Fatalf("generated:\n%s\nwant:\n%s", first, want)
	}
	validated = nil
	changed, err = generator.Generate(context.Background(), root, manifest, output)
	if err != nil || changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	after, err := os.Stat(output)
	if err != nil {
		t.Fatal(err)
	}
	if !before.ModTime().Equal(after.ModTime()) {
		t.Fatalf("mtime changed: before=%v after=%v", before.ModTime(), after.ModTime())
	}
}

func TestGeneratePreservesOldFileWhenPackageValidationFails(t *testing.T) {
	root := nodegenRoot(t)
	output := filepath.Join(root, "nodes_gen.go")
	if err := os.WriteFile(output, []byte("old-content"), 0o600); err != nil {
		t.Fatal(err)
	}
	wantErr := errors.New("package unavailable")
	generator := Generator{ListPackage: func(_ context.Context, _, importPath string) error {
		if importPath == "example.com/studio/extensions/zeta" {
			return wantErr
		}
		return nil
	}}
	manifest := nodemanifest.Manifest{APIVersion: agentnode.APIVersion, Nodes: []nodemanifest.NodePackage{
		{Package: "example.com/studio/extensions/alpha"},
		{Package: "example.com/studio/extensions/zeta"},
	}}
	changed, err := generator.Generate(context.Background(), root, manifest, output)
	if changed || !errors.Is(err, wantErr) {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	data, readErr := os.ReadFile(output)
	if readErr != nil {
		t.Fatal(readErr)
	}
	if got, want := string(data), "old-content"; got != want {
		t.Fatalf("output=%q, want %q", got, want)
	}
	entries, readDirErr := os.ReadDir(root)
	if readDirErr != nil {
		t.Fatal(readDirErr)
	}
	if len(entries) != 2 || entries[0].Name() != "go.mod" || entries[1].Name() != "nodes_gen.go" {
		t.Fatalf("unexpected files after failure: %v", entries)
	}
}

func TestGenerateEmptyManifestProducesCompilableEntryPoint(t *testing.T) {
	root := nodegenRoot(t)
	output := filepath.Join(root, "nodes_gen.go")
	changed, err := (Generator{}).Generate(context.Background(), root, nodemanifest.Manifest{
		APIVersion: agentnode.APIVersion,
		Nodes:      []nodemanifest.NodePackage{},
	}, output)
	if err != nil || !changed {
		t.Fatalf("changed=%v err=%v", changed, err)
	}
	data, err := os.ReadFile(output)
	if err != nil {
		t.Fatal(err)
	}
	want := "// Code generated by agent-studio generate; DO NOT EDIT.\n\npackage generated\n\nimport \"github.com/yyl1212/agent-studio/sdk/go/agentnode\"\n\nfunc RegisterNodes(agentnode.Registrar) error {\n\treturn nil\n}\n"
	if string(data) != want {
		t.Fatalf("generated:\n%s\nwant:\n%s", data, want)
	}
}

func nodegenRoot(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/studio\n\ngo 1.26.0\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}

func TestGenerateRejectsPackagesOutsideDirectExtensions(t *testing.T) {
	for _, importPath := range []string{
		"example.com/external/echo",
		"example.com/studio/extensions/team/echo",
		"example.com/studio/apps/api/internal/generated",
	} {
		t.Run(importPath, func(t *testing.T) {
			root := t.TempDir()
			if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/studio\n\ngo 1.26.0\n"), 0o644); err != nil {
				t.Fatal(err)
			}
			output := filepath.Join(root, "nodes_gen.go")
			if err := os.WriteFile(output, []byte("old"), 0o644); err != nil {
				t.Fatal(err)
			}
			called := false
			_, err := (Generator{ListPackage: func(context.Context, string, string) error {
				called = true
				return nil
			}}).Generate(context.Background(), root, nodemanifest.Manifest{
				APIVersion: agentnode.APIVersion,
				Nodes:      []nodemanifest.NodePackage{{Package: importPath}},
			}, output)
			if err == nil || called {
				t.Fatalf("error=%v listCalled=%v", err, called)
			}
			data, readErr := os.ReadFile(output)
			if readErr != nil || string(data) != "old" {
				t.Fatalf("output=%q err=%v", data, readErr)
			}
		})
	}
}

func TestGenerateRejectsSymlinkedOutputDirectory(t *testing.T) {
	root := nodegenRoot(t)
	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(root, "generated")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	_, err := (Generator{}).Generate(context.Background(), root, nodemanifest.Manifest{
		APIVersion: agentnode.APIVersion,
		Nodes:      []nodemanifest.NodePackage{},
	}, filepath.Join(root, "generated", "nodes_gen.go"))
	if err == nil || !strings.Contains(err.Error(), "symbolic link") {
		t.Fatalf("error=%v", err)
	}
	if _, statErr := os.Stat(filepath.Join(outside, "nodes_gen.go")); !errors.Is(statErr, os.ErrNotExist) {
		t.Fatalf("outside file exists: %v", statErr)
	}
}
